# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.Any do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :type
  ]

  @type t :: %__MODULE__{
    :type => String.t | nil
  }
end

defimpl Poison.Decoder, for: OpenFGA.Model.Any do
  def decode(value, _options) do
    value
  end
end
