# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.AssertionTupleKey do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :object,
    :relation,
    :user
  ]

  @type t :: %__MODULE__{
          :object => String.t(),
          :relation => String.t(),
          :user => String.t()
        }

  def decode(value) do
    value
  end
end
