# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.Assertion do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :tuple_key,
    :expectation,
    :contextual_tuples,
    :context
  ]

  @type t :: %__MODULE__{
    :tuple_key => OpenFGA.Model.AssertionTupleKey.t,
    :expectation => boolean(),
    :contextual_tuples => [OpenFGA.Model.TupleKey.t] | nil,
    :context => map() | nil
  }

  alias OpenFGA.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:tuple_key, :struct, OpenFGA.Model.AssertionTupleKey)
     |> Deserializer.deserialize(:contextual_tuples, :list, OpenFGA.Model.TupleKey)
  end
end

