# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.AuthorizationModel do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :schema_version,
    :type_definitions,
    :conditions
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :schema_version => String.t,
    :type_definitions => [OpenFGA.Model.TypeDefinition.t],
    :conditions => %{optional(String.t) => OpenFGA.Model.Condition.t} | nil
  }
end

defimpl Poison.Decoder, for: OpenFGA.Model.AuthorizationModel do
  import OpenFGA.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:type_definitions, :list, OpenFGA.Model.TypeDefinition, options)
    |> deserialize(:conditions, :map, OpenFGA.Model.Condition, options)
  end
end

