# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.AuthorizationModel do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :schema_version,
    :type_definitions,
    :conditions
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :schema_version => String.t,
    :type_definitions => [OpenFGA.Model.TypeDefinition.t],
    :conditions => %{optional(String.t) => OpenFGA.Model.Condition.t} | nil
  }

  alias OpenFGA.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:type_definitions, :list, OpenFGA.Model.TypeDefinition)
     |> Deserializer.deserialize(:conditions, :map, OpenFGA.Model.Condition)
  end
end

