# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.BatchCheckRequest do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :checks,
    :authorization_model_id,
    :consistency
  ]

  @type t :: %__MODULE__{
    :checks => [OpenFGA.Model.BatchCheckItem.t],
    :authorization_model_id => String.t | nil,
    :consistency => OpenFGA.Model.ConsistencyPreference.t | nil
  }

  alias OpenFGA.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:checks, :list, OpenFGA.Model.BatchCheckItem)
     |> Deserializer.deserialize(:consistency, :struct, OpenFGA.Model.ConsistencyPreference)
  end
end

