# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.BatchCheckItem do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :tuple_key,
    :contextual_tuples,
    :context,
    :correlation_id
  ]

  @type t :: %__MODULE__{
    :tuple_key => OpenFGA.Model.CheckRequestTupleKey.t,
    :contextual_tuples => OpenFGA.Model.ContextualTupleKeys.t | nil,
    :context => map() | nil,
    :correlation_id => String.t
  }

  alias OpenFGA.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:tuple_key, :struct, OpenFGA.Model.CheckRequestTupleKey)
     |> Deserializer.deserialize(:contextual_tuples, :struct, OpenFGA.Model.ContextualTupleKeys)
  end
end

