# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.CheckError do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :inputError,
    :internalError,
    :message
  ]

  @type t :: %__MODULE__{
    :inputError => OpenFGA.Model.ErrorCode.t | nil,
    :internalError => OpenFGA.Model.InternalErrorCode.t | nil,
    :message => String.t | nil
  }

  alias OpenFGA.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:inputError, :struct, OpenFGA.Model.ErrorCode)
     |> Deserializer.deserialize(:internalError, :struct, OpenFGA.Model.InternalErrorCode)
  end
end

