# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.CheckResponse do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :allowed,
    :resolution
  ]

  @type t :: %__MODULE__{
    :allowed => boolean() | nil,
    :resolution => String.t | nil
  }

  def decode(value) do
    value
  end
end

