# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.Computed do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :userset
  ]

  @type t :: %__MODULE__{
    :userset => String.t
  }

  def decode(value) do
    value
  end
end

