# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.ConditionParamTypeRef do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :type_name,
    :generic_types
  ]

  @type t :: %__MODULE__{
    :type_name => OpenFGA.Model.TypeName.t,
    :generic_types => [OpenFGA.Model.ConditionParamTypeRef.t] | nil
  }
end

defimpl Poison.Decoder, for: OpenFGA.Model.ConditionParamTypeRef do
  import OpenFGA.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:type_name, :struct, OpenFGA.Model.TypeName, options)
    |> deserialize(:generic_types, :list, OpenFGA.Model.ConditionParamTypeRef, options)
  end
end

