# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.ConditionParamTypeRef do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :type_name,
    :generic_types
  ]

  @type t :: %__MODULE__{
    :type_name => OpenFGA.Model.TypeName.t,
    :generic_types => [OpenFGA.Model.ConditionParamTypeRef.t] | nil
  }

  alias OpenFGA.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:type_name, :struct, OpenFGA.Model.TypeName)
     |> Deserializer.deserialize(:generic_types, :list, OpenFGA.Model.ConditionParamTypeRef)
  end
end

