# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.ConditionMetadata do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :module,
    :source_info
  ]

  @type t :: %__MODULE__{
    :module => String.t | nil,
    :source_info => OpenFGA.Model.SourceInfo.t | nil
  }
end

defimpl Poison.Decoder, for: OpenFGA.Model.ConditionMetadata do
  import OpenFGA.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:source_info, :struct, OpenFGA.Model.SourceInfo, options)
  end
end

