# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.Condition do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :name,
    :expression,
    :parameters,
    :metadata
  ]

  @type t :: %__MODULE__{
    :name => String.t,
    :expression => String.t,
    :parameters => %{optional(String.t) => OpenFGA.Model.ConditionParamTypeRef.t} | nil,
    :metadata => OpenFGA.Model.ConditionMetadata.t | nil
  }
end

defimpl Poison.Decoder, for: OpenFGA.Model.Condition do
  import OpenFGA.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:parameters, :map, OpenFGA.Model.ConditionParamTypeRef, options)
    |> deserialize(:metadata, :struct, OpenFGA.Model.ConditionMetadata, options)
  end
end

