# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.Condition do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :name,
    :expression,
    :parameters,
    :metadata
  ]

  @type t :: %__MODULE__{
    :name => String.t,
    :expression => String.t,
    :parameters => %{optional(String.t) => OpenFGA.Model.ConditionParamTypeRef.t} | nil,
    :metadata => OpenFGA.Model.ConditionMetadata.t | nil
  }

  alias OpenFGA.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:parameters, :map, OpenFGA.Model.ConditionParamTypeRef)
     |> Deserializer.deserialize(:metadata, :struct, OpenFGA.Model.ConditionMetadata)
  end
end

