# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.ContextualTupleKeys do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :tuple_keys
  ]

  @type t :: %__MODULE__{
    :tuple_keys => [OpenFGA.Model.TupleKey.t]
  }

  alias OpenFGA.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:tuple_keys, :list, OpenFGA.Model.TupleKey)
  end
end

