# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.Difference do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :base,
    :subtract
  ]

  @type t :: %__MODULE__{
    :base => OpenFGA.Model.Userset.t,
    :subtract => OpenFGA.Model.Userset.t
  }

  alias OpenFGA.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:base, :struct, OpenFGA.Model.Userset)
     |> Deserializer.deserialize(:subtract, :struct, OpenFGA.Model.Userset)
  end
end

