# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.ExpandResponse do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :tree
  ]

  @type t :: %__MODULE__{
    :tree => OpenFGA.Model.UsersetTree.t | nil
  }

  alias OpenFGA.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:tree, :struct, OpenFGA.Model.UsersetTree)
  end
end

