# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.ExpandRequestTupleKey do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :relation,
    :object
  ]

  @type t :: %__MODULE__{
    :relation => String.t,
    :object => String.t
  }
end

defimpl Poison.Decoder, for: OpenFGA.Model.ExpandRequestTupleKey do
  def decode(value, _options) do
    value
  end
end

