# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.ExpandRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :tuple_key,
    :authorization_model_id,
    :consistency
  ]

  @type t :: %__MODULE__{
    :tuple_key => OpenFGA.Model.ExpandRequestTupleKey.t,
    :authorization_model_id => String.t | nil,
    :consistency => OpenFGA.Model.ConsistencyPreference.t | nil
  }
end

defimpl Poison.Decoder, for: OpenFGA.Model.ExpandRequest do
  import OpenFGA.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:tuple_key, :struct, OpenFGA.Model.ExpandRequestTupleKey, options)
    |> deserialize(:consistency, :struct, OpenFGA.Model.ConsistencyPreference, options)
  end
end

