# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.FgaObject do
  @moduledoc """
  Object represents an OpenFGA Object.  An Object is composed of a type and identifier (e.g. 'document:1')  See https://openfga.dev/docs/concepts#what-is-an-object
  """

  @derive [Poison.Encoder]
  defstruct [
    :type,
    :id
  ]

  @type t :: %__MODULE__{
    :type => String.t,
    :id => String.t
  }
end

defimpl Poison.Decoder, for: OpenFGA.Model.FgaObject do
  def decode(value, _options) do
    value
  end
end

