# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.ListObjectsRequest do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :authorization_model_id,
    :type,
    :relation,
    :user,
    :contextual_tuples,
    :context,
    :consistency
  ]

  @type t :: %__MODULE__{
    :authorization_model_id => String.t | nil,
    :type => String.t,
    :relation => String.t,
    :user => String.t,
    :contextual_tuples => OpenFGA.Model.ContextualTupleKeys.t | nil,
    :context => map() | nil,
    :consistency => OpenFGA.Model.ConsistencyPreference.t | nil
  }

  alias OpenFGA.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:contextual_tuples, :struct, OpenFGA.Model.ContextualTupleKeys)
     |> Deserializer.deserialize(:consistency, :struct, OpenFGA.Model.ConsistencyPreference)
  end
end

