# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.ListUsersRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :authorization_model_id,
    :object,
    :relation,
    :user_filters,
    :contextual_tuples,
    :context,
    :consistency
  ]

  @type t :: %__MODULE__{
    :authorization_model_id => String.t | nil,
    :object => OpenFGA.Model.FgaObject.t,
    :relation => String.t,
    :user_filters => [OpenFGA.Model.UserTypeFilter.t],
    :contextual_tuples => [OpenFGA.Model.TupleKey.t] | nil,
    :context => map() | nil,
    :consistency => OpenFGA.Model.ConsistencyPreference.t | nil
  }
end

defimpl Poison.Decoder, for: OpenFGA.Model.ListUsersRequest do
  import OpenFGA.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:object, :struct, OpenFGA.Model.FgaObject, options)
    |> deserialize(:user_filters, :list, OpenFGA.Model.UserTypeFilter, options)
    |> deserialize(:contextual_tuples, :list, OpenFGA.Model.TupleKey, options)
    |> deserialize(:consistency, :struct, OpenFGA.Model.ConsistencyPreference, options)
  end
end

