# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.ListObjectsResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :objects
  ]

  @type t :: %__MODULE__{
    :objects => [String.t]
  }
end

defimpl Poison.Decoder, for: OpenFGA.Model.ListObjectsResponse do
  def decode(value, _options) do
    value
  end
end

