# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.ListUsersRequest do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :authorization_model_id,
    :object,
    :relation,
    :user_filters,
    :contextual_tuples,
    :context,
    :consistency
  ]

  @type t :: %__MODULE__{
    :authorization_model_id => String.t | nil,
    :object => OpenFGA.Model.FgaObject.t,
    :relation => String.t,
    :user_filters => [OpenFGA.Model.UserTypeFilter.t],
    :contextual_tuples => [OpenFGA.Model.TupleKey.t] | nil,
    :context => map() | nil,
    :consistency => OpenFGA.Model.ConsistencyPreference.t | nil
  }

  alias OpenFGA.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:object, :struct, OpenFGA.Model.FgaObject)
     |> Deserializer.deserialize(:user_filters, :list, OpenFGA.Model.UserTypeFilter)
     |> Deserializer.deserialize(:contextual_tuples, :list, OpenFGA.Model.TupleKey)
     |> Deserializer.deserialize(:consistency, :struct, OpenFGA.Model.ConsistencyPreference)
  end
end

