# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.ListStoresResponse do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :stores,
    :continuation_token
  ]

  @type t :: %__MODULE__{
    :stores => [OpenFGA.Model.Store.t],
    :continuation_token => String.t
  }

  alias OpenFGA.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:stores, :list, OpenFGA.Model.Store)
  end
end

