# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.ListUsersResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :users
  ]

  @type t :: %__MODULE__{
    :users => [OpenFGA.Model.User.t]
  }
end

defimpl Poison.Decoder, for: OpenFGA.Model.ListUsersResponse do
  import OpenFGA.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:users, :list, OpenFGA.Model.User, options)
  end
end

