# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.ListUsersResponse do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :users
  ]

  @type t :: %__MODULE__{
    :users => [OpenFGA.Model.User.t]
  }

  alias OpenFGA.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:users, :list, OpenFGA.Model.User)
  end
end

