# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.Metadata do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :relations,
    :module,
    :source_info
  ]

  @type t :: %__MODULE__{
    :relations => %{optional(String.t) => OpenFGA.Model.RelationMetadata.t} | nil,
    :module => String.t | nil,
    :source_info => OpenFGA.Model.SourceInfo.t | nil
  }

  alias OpenFGA.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:relations, :map, OpenFGA.Model.RelationMetadata)
     |> Deserializer.deserialize(:source_info, :struct, OpenFGA.Model.SourceInfo)
  end
end

