# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.Nodes do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :nodes
  ]

  @type t :: %__MODULE__{
    :nodes => [OpenFGA.Model.Node.t]
  }

  alias OpenFGA.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:nodes, :list, OpenFGA.Model.Node)
  end
end

