# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.ReadRequestTupleKey do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :user,
    :relation,
    :object
  ]

  @type t :: %__MODULE__{
    :user => String.t | nil,
    :relation => String.t | nil,
    :object => String.t | nil
  }

  def decode(value) do
    value
  end
end

