# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.ReadAuthorizationModelsResponse do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :authorization_models,
    :continuation_token
  ]

  @type t :: %__MODULE__{
    :authorization_models => [OpenFGA.Model.AuthorizationModel.t],
    :continuation_token => String.t | nil
  }

  alias OpenFGA.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:authorization_models, :list, OpenFGA.Model.AuthorizationModel)
  end
end

