# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.ReadChangesResponse do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :changes,
    :continuation_token
  ]

  @type t :: %__MODULE__{
    :changes => [OpenFGA.Model.TupleChange.t],
    :continuation_token => String.t | nil
  }

  alias OpenFGA.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:changes, :list, OpenFGA.Model.TupleChange)
  end
end

