# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.ReadRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :tuple_key,
    :page_size,
    :continuation_token,
    :consistency
  ]

  @type t :: %__MODULE__{
    :tuple_key => OpenFGA.Model.ReadRequestTupleKey.t | nil,
    :page_size => integer() | nil,
    :continuation_token => String.t | nil,
    :consistency => OpenFGA.Model.ConsistencyPreference.t | nil
  }
end

defimpl Poison.Decoder, for: OpenFGA.Model.ReadRequest do
  import OpenFGA.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:tuple_key, :struct, OpenFGA.Model.ReadRequestTupleKey, options)
    |> deserialize(:consistency, :struct, OpenFGA.Model.ConsistencyPreference, options)
  end
end

