# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.RelationshipCondition do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :name,
    :context
  ]

  @type t :: %__MODULE__{
    :name => String.t,
    :context => map() | nil
  }
end

defimpl Poison.Decoder, for: OpenFGA.Model.RelationshipCondition do
  def decode(value, _options) do
    value
  end
end

