# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.RelationMetadata do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :directly_related_user_types,
    :module,
    :source_info
  ]

  @type t :: %__MODULE__{
    :directly_related_user_types => [OpenFGA.Model.RelationReference.t] | nil,
    :module => String.t | nil,
    :source_info => OpenFGA.Model.SourceInfo.t | nil
  }
end

defimpl Poison.Decoder, for: OpenFGA.Model.RelationMetadata do
  import OpenFGA.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:directly_related_user_types, :list, OpenFGA.Model.RelationReference, options)
    |> deserialize(:source_info, :struct, OpenFGA.Model.SourceInfo, options)
  end
end

