# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.RelationshipCondition do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :name,
    :context
  ]

  @type t :: %__MODULE__{
    :name => String.t,
    :context => map() | nil
  }

  def decode(value) do
    value
  end
end

