# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.RelationReference do
  @moduledoc """
  RelationReference represents a relation of a particular object type (e.g. 'document#viewer').
  """

  @derive Jason.Encoder
  defstruct [
    :type,
    :relation,
    :wildcard,
    :condition
  ]

  @type t :: %__MODULE__{
    :type => String.t,
    :relation => String.t | nil,
    :wildcard => map() | nil,
    :condition => String.t | nil
  }

  def decode(value) do
    value
  end
end

