# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.RelationMetadata do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :directly_related_user_types,
    :module,
    :source_info
  ]

  @type t :: %__MODULE__{
    :directly_related_user_types => [OpenFGA.Model.RelationReference.t] | nil,
    :module => String.t | nil,
    :source_info => OpenFGA.Model.SourceInfo.t | nil
  }

  alias OpenFGA.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:directly_related_user_types, :list, OpenFGA.Model.RelationReference)
     |> Deserializer.deserialize(:source_info, :struct, OpenFGA.Model.SourceInfo)
  end
end

