# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.SourceInfo do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :file
  ]

  @type t :: %__MODULE__{
    :file => String.t | nil
  }

  def decode(value) do
    value
  end
end

