# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.Status do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :code,
    :message,
    :details
  ]

  @type t :: %__MODULE__{
    :code => integer() | nil,
    :message => String.t | nil,
    :details => [OpenFGA.Model.Any.t] | nil
  }

  alias OpenFGA.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:details, :list, OpenFGA.Model.Any)
  end
end

