# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.Store do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :name,
    :created_at,
    :updated_at,
    :deleted_at
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :name => String.t,
    :created_at => DateTime.t,
    :updated_at => DateTime.t,
    :deleted_at => DateTime.t | nil
  }
end

defimpl Poison.Decoder, for: OpenFGA.Model.Store do
  def decode(value, _options) do
    value
  end
end

