# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.TupleKey do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :user,
    :relation,
    :object,
    :condition
  ]

  @type t :: %__MODULE__{
    :user => String.t,
    :relation => String.t,
    :object => String.t,
    :condition => OpenFGA.Model.RelationshipCondition.t | nil
  }
end

defimpl Poison.Decoder, for: OpenFGA.Model.TupleKey do
  import OpenFGA.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:condition, :struct, OpenFGA.Model.RelationshipCondition, options)
  end
end

