# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.Tuple do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :key,
    :timestamp
  ]

  @type t :: %__MODULE__{
    :key => OpenFGA.Model.TupleKey.t,
    :timestamp => DateTime.t
  }

  alias OpenFGA.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:key, :struct, OpenFGA.Model.TupleKey)
     |> Deserializer.deserialize(:timestamp, :datetime, nil)
  end
end

