# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.TupleKey do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :user,
    :relation,
    :object,
    :condition
  ]

  @type t :: %__MODULE__{
    :user => String.t,
    :relation => String.t,
    :object => String.t,
    :condition => OpenFGA.Model.RelationshipCondition.t | nil
  }

  alias OpenFGA.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:condition, :struct, OpenFGA.Model.RelationshipCondition)
  end
end

