# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.TupleChange do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :tuple_key,
    :operation,
    :timestamp
  ]

  @type t :: %__MODULE__{
    :tuple_key => OpenFGA.Model.TupleKey.t,
    :operation => OpenFGA.Model.TupleOperation.t,
    :timestamp => DateTime.t
  }

  alias OpenFGA.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:tuple_key, :struct, OpenFGA.Model.TupleKey)
     |> Deserializer.deserialize(:operation, :struct, OpenFGA.Model.TupleOperation)
     |> Deserializer.deserialize(:timestamp, :datetime, nil)
  end
end

