# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.TupleToUserset do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :tupleset,
    :computedUserset
  ]

  @type t :: %__MODULE__{
    :tupleset => OpenFGA.Model.ObjectRelation.t,
    :computedUserset => OpenFGA.Model.ObjectRelation.t
  }

  alias OpenFGA.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:tupleset, :struct, OpenFGA.Model.ObjectRelation)
     |> Deserializer.deserialize(:computedUserset, :struct, OpenFGA.Model.ObjectRelation)
  end
end

