# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.TypeDefinition do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :type,
    :relations,
    :metadata
  ]

  @type t :: %__MODULE__{
    :type => String.t,
    :relations => %{optional(String.t) => OpenFGA.Model.Userset.t} | nil,
    :metadata => OpenFGA.Model.Metadata.t | nil
  }

  alias OpenFGA.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:relations, :map, OpenFGA.Model.Userset)
     |> Deserializer.deserialize(:metadata, :struct, OpenFGA.Model.Metadata)
  end
end

