# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.UsersetTree do
  @moduledoc """
  A UsersetTree contains the result of an Expansion.
  """

  @derive Jason.Encoder
  defstruct [
    :root
  ]

  @type t :: %__MODULE__{
    :root => OpenFGA.Model.Node.t | nil
  }

  alias OpenFGA.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:root, :struct, OpenFGA.Model.Node)
  end
end

