# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.UsersetUser do
  @moduledoc """
  Userset.  A set or group of users, represented in the `<type>:<id>#<relation>` format  `group:fga#member` represents all members of group FGA, not to be confused by `group:fga` which represents the group itself as a specific object.  See: https://openfga.dev/docs/modeling/building-blocks/usersets#what-is-a-userset
  """

  @derive Jason.Encoder
  defstruct [
    :type,
    :id,
    :relation
  ]

  @type t :: %__MODULE__{
    :type => String.t,
    :id => String.t,
    :relation => String.t
  }

  def decode(value) do
    value
  end
end

