# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.UserTypeFilter do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :type,
    :relation
  ]

  @type t :: %__MODULE__{
    :type => String.t,
    :relation => String.t | nil
  }
end

defimpl Poison.Decoder, for: OpenFGA.Model.UserTypeFilter do
  def decode(value, _options) do
    value
  end
end

