# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.User do
  @moduledoc """
  User.  Represents any possible value for a user (subject or principal). Can be a: - Specific user object e.g.: 'user:will', 'folder:marketing', 'org:contoso', ...) - Specific userset (e.g. 'group:engineering#member') - Public-typed wildcard (e.g. 'user:*')  See https://openfga.dev/docs/concepts#what-is-a-user
  """

  @derive [Poison.Encoder]
  defstruct [
    :object,
    :userset,
    :wildcard
  ]

  @type t :: %__MODULE__{
    :object => OpenFGA.Model.FgaObject.t | nil,
    :userset => OpenFGA.Model.UsersetUser.t | nil,
    :wildcard => OpenFGA.Model.TypedWildcard.t | nil
  }
end

defimpl Poison.Decoder, for: OpenFGA.Model.User do
  import OpenFGA.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:object, :struct, OpenFGA.Model.FgaObject, options)
    |> deserialize(:userset, :struct, OpenFGA.Model.UsersetUser, options)
    |> deserialize(:wildcard, :struct, OpenFGA.Model.TypedWildcard, options)
  end
end

