# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.WriteAuthorizationModelResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :authorization_model_id
  ]

  @type t :: %__MODULE__{
    :authorization_model_id => String.t
  }
end

defimpl Poison.Decoder, for: OpenFGA.Model.WriteAuthorizationModelResponse do
  def decode(value, _options) do
    value
  end
end

