# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.WriteRequest do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :writes,
    :deletes,
    :authorization_model_id
  ]

  @type t :: %__MODULE__{
    :writes => OpenFGA.Model.WriteRequestWrites.t | nil,
    :deletes => OpenFGA.Model.WriteRequestDeletes.t | nil,
    :authorization_model_id => String.t | nil
  }

  alias OpenFGA.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:writes, :struct, OpenFGA.Model.WriteRequestWrites)
     |> Deserializer.deserialize(:deletes, :struct, OpenFGA.Model.WriteRequestDeletes)
  end
end

