# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.WriteRequestDeletes do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :tuple_keys
  ]

  @type t :: %__MODULE__{
    :tuple_keys => [OpenFGA.Model.TupleKeyWithoutCondition.t]
  }
end

defimpl Poison.Decoder, for: OpenFGA.Model.WriteRequestDeletes do
  import OpenFGA.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:tuple_keys, :list, OpenFGA.Model.TupleKeyWithoutCondition, options)
  end
end

